name: Snyk SCA & Code CLI Monitor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # Define Node.js versions here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Snyk CLI and snyk-to-html
        run: |
          npm install snyk -g
          npm install snyk-to-html -g

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_AUTH }}

      - name: Snyk Open Source test and monitor
        run: |
          snyk test || true
          snyk monitor

      - name: Snyk Code test
        run: snyk code test || true
        
      - name: Snyk IaC test
        run: snyk iac test || true
